sudo: required

services:
  - docker

script:
  - |
    docker-compose up --build

    sleep 60
    
    APK_DEBUG="./apk/app-debug.apk";
    APK_RELEASE="./apk/app-release.apk";
    AAB_DEBUG="./apk/app-debug.aab";
    AAB_RELEASE="./apk/app-release.aab";

    ls -la ./apk/

    if [ ! -f "${APK_DEBUG}" ]; then
      echo "Not exists debug apk"
      exit 1;
    fi;

    if [ ! -f "${APK_RELEASE}" ]; then
      echo "Not exists release apk"
      exit 1;
    fi;

    if [ ! -f "${AAB_DEBUG}" ]; then
      echo "Not exists debug aab"
      exit 1;
    fi;

    if [ ! -f "${AAB_RELEASE}" ]; then
      echo "Not exists release aab"
      exit 1;
    fi;