version: '3'

services:
    cordova:
        build: .
        command: all
        image: likesistemas/cordova:dev
        volumes:
            - ./apk/:/root/apk/
            - ./www/:/root/www/
            - ./.env-app:/root/app/.env-app