version: '3'

services:
    cordova:
        build: .
        command: all
        image: likesistemas/cordova:dev
        volumes:
            - ./apk/:/root/apk/
            - ./www/:/root/www/
            - ./.env-app:/root/app/.env-app
    
    debug:
        build: .
        image: likesistemas/cordova:dev
        working_dir: /root/
        command: bash
        volumes:
            - ./www/:/root/www/
        stdin_open: true
        tty: true